WebDT/Models/DangNhap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangNhap
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> buyLastDate { get; set; }
        public Nullable<int> countOrder { get; set; }
        public Nullable<double> amountSpent { get; set; }
        public Nullable<double> accountNumber { get; set; }
    }
}

WebDT/Areas/admin/Controllers/DangNhapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebDT.Models;

namespace WebDT.Areas.admin.Controllers
{
    public class DangNhapsController : Controller
    {
       
        private WebMayTinhEntities db = new WebMayTinhEntities();
        // GET: admin/DangNhaps
        public ActionResult Index()
        {
                var list = from DSKhachHang in db.DangNhaps
                           //where DSKhachHang.Quyenadmin == null && DSKhachHang.Quyenuser == null
                           select DSKhachHang;
                return View(list.ToList());
        }

        // GET: admin/DangNhaps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DangNhap dangNhap = db.DangNhaps.Find(id);
            if (dangNhap == null)
            {
                return HttpNotFound();
            }
            return View(dangNhap);
        }

        //Chart detail 
        public ActionResult UserChart()
        {
            var model = db.DangNhaps.Where(x => x.buyLastDate != null).ToList();
            var lstUser = new List<userChart>();

            //Tính ngày mua hàng gần nhất
            foreach(var item in model)
            {
                var userChart = new userChart();
                TimeSpan time = DateTime.Now - item.buyLastDate.Value;
                int Tongngay = time.Days;
                int soDonHang = int.Parse(item.countOrder.ToString());
                float soTienMua = float.Parse(item.amountSpent.ToString());
                userChart.Tongngay = Tongngay;
                userChart.soDonHang = soDonHang;
                userChart.soTienMua = soTienMua / 10000000;
                userChart.name = item.name;
                
                lstUser.Add(userChart);
            }
            return Json(lstUser, JsonRequestBehavior.AllowGet);
        }

        // GET: admin/DangNhaps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/DangNhaps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,username,password,name,address,email,phone,status")] DangNhap dangNhap)
        {
            if (ModelState.IsValid)
            {
                db.DangNhaps.Add(dangNhap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dangNhap);
        }

        // GET: admin/DangNhaps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DangNhap dangNhap = db.DangNhaps.Find(id);
            if (dangNhap == null)
            {
                return HttpNotFound();
            }
            return View(dangNhap);
        }

        // POST: admin/DangNhaps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,username,password,name,address,email,phone,status")] DangNhap dangNhap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dangNhap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dangNhap);
        }

        // GET: admin/DangNhaps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DangNhap dangNhap = db.DangNhaps.Find(id);
            if (dangNhap == null)
            {
                return HttpNotFound();
            }
            return View(dangNhap);
        }

        // POST: admin/DangNhaps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DangNhap dangNhap = db.DangNhaps.Find(id);
            db.DangNhaps.Remove(dangNhap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            return Redirect("http://localhost:54398");
        }
    }
}

WebDT/Areas/admin/Views/DangNhaps/Create.cshtml
@model WebDT.Models.DangNhap

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Mylayout.cshtml";
}

<br />
<h2 style="margin-left:30%">Thêm tài khoản</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tài khoản", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Họ Tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("E-Mail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.status)
                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại danh sách", "Index")
</div>

WebDT/Areas/admin/Views/DangNhaps/Delete.cshtml
@model WebDT.Models.DangNhap

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Mylayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">
            <div class="panel-heading">
                Xoá
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div>
                    <h3 style="margin-left:35%">Bạn có thật sự muốn xoá ?</h3>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayName("Tài Khoản:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.username)
                        </dd>

                        <dt>
                            @Html.DisplayName("Mật khẩu:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.password)
                        </dd>

                        <dt>
                            @Html.DisplayName("Họ Tên:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.name)
                        </dd>

                        <dt>
                            @Html.DisplayName("Địa Chỉ:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.address)
                        </dd>

                        <dt>
                            @Html.DisplayName("E-Mail:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.email)
                        </dd>

                        <dt>
                            @Html.DisplayName("Số Điện Thoại:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.phone)
                        </dd>

                        <dt>
                            @Html.DisplayName("Trạng thái:")
                        </dt>

                        <dd>
                            @(Model.status.GetValueOrDefault(false) ? "Hiển Thị" : "Ẩn")
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Xóa" class="btn btn-default" /> |
                            @Html.ActionLink("Quay lại danh sách", "Index")
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

WebDT/Areas/admin/Views/DangNhaps/Details.cshtml
@model WebDT.Models.DangNhap

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_Mylayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">

            <div class="panel-heading">
                Thông Tin
            </div>

            <!-- /.panel-heading -->
            <div class="panel-body">
                @using (Html.BeginForm("Details", "DangNhaps", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div>
                        <h4 style="margin-left:35%">THÔNG TIN CHI TÀI KHOẢN</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayName("Tài Khoản:")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.username)
                            </dd>

                            <dt>
                                @Html.DisplayName("Mật khẩu:")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.password)
                            </dd>

                            <dt>
                                @Html.DisplayName("Họ Tên:")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.name)
                            </dd>

                            <dt>
                                @Html.DisplayName("Địa Chỉ:")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.address)
                            </dd>

                            <dt>
                                @Html.DisplayName("E-Mail:")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.email)
                            </dd>

                            <dt>
                                @Html.DisplayName("Số Điện Thoại:")
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.phone)
                            </dd>

                            <dt>
                                @Html.DisplayName("Trạng thái:")
                            </dt>

                            <dd>
                                @(Model.status.GetValueOrDefault(false) ? "Hiển Thị" : "Ẩn")
                            </dd>

                        </dl>
                    </div>
                    <p>
                        @Html.ActionLink("Sửa Lại", "Edit", new { id = Model.id }) |
                        @Html.ActionLink("Quay lại", "Index")
                    </p>
                }
            </div>
            
        </div>
    </div>
</div>

@section _Footer{
     
}

WebDT/Areas/admin/Views/DangNhaps/Edit.cshtml
@model WebDT.Models.DangNhap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Mylayout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">

            <!-- /.panel-heading -->
            <div class="panel-body">
                @using (Html.BeginForm("Edit", "DangNhaps", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4 style="margin-left:35%">SỬA THÔNG TIN TÀI KHOẢN</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="form-group">
                            @Html.Label("Tài khoản:", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Mật khẩu:", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Họ Tên:", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Địa Chỉ:", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("E-Mail:", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Số Điện Thoại:", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Trạng Thái:", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.status)
                                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Lưu" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Quay lại danh sách", "Index")
                </div>
            </div>
        </div>
    </div>
</div>

WebDT/Areas/admin/Views/DangNhaps/Index.cshtml
@using WebDT.Help
@model IEnumerable<WebDT.Models.DangNhap>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Mylayout.cshtml";
}
@section _header
{
    <!--DataTables css-->
    <link href="~/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet" />
    <!--DataTables responsive css-->
    <link href="~/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet" />
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Quản lý
            </div>
            <!--/.panel-heading-->
            <div class="panel-body">
                <p>
                    @Html.ActionLink("Thêm mới", "Create")
                </p>
                <table class="table table-striped table-bordered table-hover" id="dataTables-example" style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                STT
                            </th>
                            <th>
                                Tài khoản
                            </th>                        
                            <th>
                                Mật khẩu
                            </th>
                            <th>
                                Họ tên
                            </th>
                            
                            <th>
                                Số điện thoại
                            </th>

                            <th>
                                Số tài khoản
                            </th>
                            <th>
                                Trạng thái
                            </th>
                            <th>Công cụ</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ var Number = 1;  }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.Raw(Number++)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.username)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.password)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.name)
                                </td>
                               
                                <td>
                                    @Html.DisplayFor(modelItem => item.phone)
                                </td>
                                
                                <td>
                                    @Html.DisplayFor(modelItem => item.accountNumber)
                                </td>

                                <td>
                                    @(item.status.GetValueOrDefault(false) ? "Hiển thị" : "Ẩn")
                                </td>
                             
                                <td>
                                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-pencil'></span>", "Sửa", "Edit", "DangNhaps", routeValues: new { id = item.id }, htmlAttributes: new { data_modal = "", @class = "btn btn-default" })
                                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-zoom-in'></span>", "Chi tiết", "Details", "DangNhaps", routeValues: new { id = item.id }, htmlAttributes: new { data_id = item.id , @class = "btn btn-default", @id="btn-detail" })
                                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Xoá", "Delete", "DangNhaps", routeValues: new { id = item.id }, htmlAttributes: new { data_modal = "", @class = "btn btn-default" })
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
                @*<div id="userChart"></div>*@
            </div>
        </div>
    </div>
</div>
@section _Footer
{
    <!-- DataTables JavaScript -->
    <script src="~/Areas/admin/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Areas/admin/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/Areas/admin/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <script src="~/Content/js/userChart.js"></script>  
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>
}