WebDT/Models/GioHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int id { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string IDKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string SDTKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> PayFormat { get; set; }
    }
}

WebDT/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebDT.Models;

namespace WebDT.Controllers
{
    public class GioHangController : Controller
    {
        WebMayTinhEntities _db = new WebMayTinhEntities();
        private const string CartSession = "CartSession";

        // GET: GioHang
        public ActionResult Index()
        {

            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);


        }
        public ActionResult ThemVaoGio(int productId, int quantity)
        {
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Product.id == productId))
                {
                    foreach (var item in list)
                    {
                        if (item.Product.id == productId)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    var item = new CartItem();
                    item.Product = _db.products.Find(productId);
                    item.Quantity = quantity;
                    list.Add(item);
                }
                Session[CartSession] = list;
            }
            else
            {
                var item = new CartItem();
                item.Product = _db.products.Find(productId);
                item.Quantity = quantity;
                var list = new List<CartItem>();
                list.Add(item);


                Session[CartSession] = list;
            }
            return RedirectToAction("");
        }
        public JsonResult Delete(int id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];
            sessionCart.RemoveAll(x => x.Product.id == id);
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }

        //Sửa số lượng
        public JsonResult Edit(string cartModel)
        {
            var JsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var cartSec = (List<CartItem>)Session[CartSession];

            foreach (var item in cartSec)
            {
                var jsonItem = JsonCart.SingleOrDefault(x => x.Product.id == item.Product.id);
                if (jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }

            Session[CartSession] = cartSec;
            return Json(new
            {
                status = true
            });
        }

        public ActionResult ThanhToan()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }

        [HttpPost]
        public ActionResult ThanhToan(int? productId, string totalPrice, string tenkhachhang, string sdt, string diachi, string email, string noidung)
        {

            var order = new GioHang();
            order.NgayTao = DateTime.Now;
            order.IDKhachHang = Session["UserName"].ToString();  
            order.DiaChi = diachi;
            order.Email = email;
            order.TenKhachHang = tenkhachhang;
            order.SDTKhachHang = sdt;
            order.NoiDung = noidung;
            order.status = true;
            if(Session[CartSession] == null)
            {
                var item = new CartItem();
                item.Product = _db.products.Find(productId);
                item.Quantity = 1;
                var list = new List<CartItem>();
                list.Add(item);

                Session[CartSession] = list;
            }

            //Lưu ngày đặt hàng, thêm tổng đơn hàng, thêm tổng tiền đã chi
            var user = _db.DangNhaps.Single(x => x.name == tenkhachhang);
            user.buyLastDate = DateTime.Now;
            user.countOrder += 1;
            user.amountSpent += float.Parse(totalPrice);
            _db.SaveChanges();
            try
            {
                _db.GioHangs.Add(order);
                _db.SaveChanges();

                var cart = (List<CartItem>)Session[CartSession];
                foreach (var i in cart)
                {
                    var orderDetail = new ChiTietGioHang();
                    orderDetail.IDSanPham = i.Product.id;
                    orderDetail.IDGioHang = order.id;
                    if (i.Product.newprice != null)
                    {
                      
                        orderDetail.Tien = i.Product.newprice * i.Quantity;
                    }
                    else
                    {
                        orderDetail.Tien = i.Product.price * i.Quantity;
                    }
                    
                    orderDetail.SoLuong = i.Quantity;

                    _db.ChiTietGioHangs.Add(orderDetail);
                    _db.SaveChanges();
                }
                //thanh toán thành công thì cho giỏ hàng bằng null
                Session[CartSession] = null;
            }
            catch
            {
                return Redirect("/loi-thanh-toan");
            }
            ViewBag.Alert = "Bạn vừa đặt hàng thành công.";
            return Redirect("/hoan-thanh");
        }
        public ActionResult Success()
        {
            
            return View();
            
        }
        public PartialViewResult HeaderCart()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return PartialView(list);
        }

        //Thanh toán online
        public ActionResult PaymentOnline(long id)
        {
            if(@Session["ten"] == null)
            {
                return Redirect("/dang-nhap");
            }
            else
            {
                var v = _db.products.SingleOrDefault(x => x.id == id);
                ViewBag.PaymentOnline = v;
                return View();
            }
        }

    }
}

WebDT/Views/GioHang/HeaderCart.cshtml
@model List<WebDT.Models.CartItem>
<div class="col-sm-6" style="width: 15%; float: right">
    <div class="shopping-item">
        <a href="/gio-hang">Giỏ hàng<i class="fa fa-shopping-cart"></i> <span class="product-count">@Model.Count</span></a>

     </div>
</div>
<!--string.Format("{0:0,0 VNĐ}",Model.Sum(m => (m.Product.price * m.Quantity))) -->

 

WebDT/Views/GioHang/Index.cshtml
@model List<WebDT.Models.CartItem>
@{
    ViewBag.Title = "Giỏ hàng";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
    double? total = 0;
}
@section jsFooter{
    <script src="~/Scripts/Controller/cartController.js"></script>
}
    
<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h1><b>Giỏ Hàng</b></h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
       @if (Session["UserName"] != null)
       {
            if (Model.Count > 0)
            {
                <table cellspacing="0" class="shop_table cart">
                    <thead>
                        <tr>

                            <th class="product-thumbnail">Hình ảnh</th>
                            <th class="product-name">Tên sản phẩm</th>
                            <th class="product-price">Giá tiền(VNĐ)</th>
                            <th class="product-quantity">Số lượng</th>
                            <th class="product-subtotal">Tổng giá(VNĐ)</th>
                            <th class="product-remove">&nbsp;</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var i in Model)
                        {
                            <tr class="cart_item">



                                <td class="product-thumbnail">
                                    <a href="#"><img width="145" height="145" alt="poster_1_up" class="shop_thumbnail" src="~/Content/img/@i.Product.img"></a>
                                </td>

                                <td class="product-name">
                                    <a href="#">@i.Product.name</a>
                                </td>

                                <td class="product-price">
                                    <span class="amount">
                                        @if (i.Product.newprice != null)
                                        {  @i.Product.newprice.GetValueOrDefault(0).ToString("N0");}
                                        else
                                        { @i.Product.price.GetValueOrDefault(0).ToString("N0"); }
                                    </span>
                                </td>

                                <td class="product-quantity">
                                    <div class="quantity buttons_added">

                                        <input type="number" size="4" class="input-text qty text txt_quantity" data-id="@i.Product.id" title="Qty" value="@i.Quantity" min="0" step="1">

                                    </div>
                                </td>

                                <td class="product-subtotal">
                                    <span class="amount">
                                        @if (i.Product.newprice != null)
                                        {
                                            @((i.Product.newprice * i.Quantity).GetValueOrDefault(0).ToString("N0"))
                                        }
                                        else
                                        {
                                            @((i.Product.price * i.Quantity).GetValueOrDefault(0).ToString("N0")) 
                                        }
                                    </span>
                                </td>
                                <td class="product-remove">
                                    <a href="#"  class="btn btn-primary btn-edit" title="Sửa số lượng"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a href="#" data-id="@i.Product.id" class="btn btn-danger btn-delete" title="Xóa mặt hàng"><i class="glyphicon glyphicon-remove"></i></a>
                                </td>


                            </tr>
                            if (i.Product.newprice != null)
                            {
                                total = total + i.Product.newprice * i.Quantity;
                            }
                            else
                            {
                                total = total + i.Product.price * i.Quantity;
                            }
                        }

                    </tbody>
                    <tr>

                        <td colspan="4"><strong>Tổng cộng </strong></td>
                        <td colspan="2"><strong>@string.Format("{0:0,0 vnđ}", total) </strong> </td>
                    </tr>
                    <tr>
                        <td class="actions" colspan="6">
                            <div class="coupon" style="width:80%">
                                <form class="#"  action="@Url.Action("ThanhToan", "GioHang")">
                                    <label for="coupon_code">Coupon:</label>
                                    <input type="text" placeholder="Coupon code" value="" id="coupon_code" class="input-text" name="coupon_code">
                                    <input type="submit" value="Phiếu Khuyến mãi" name="apply_coupon" class="button">
                                    <input type="submit" value="Đặt hàng" name="proceed" class="checkout-button button alt wc-forward">
                                </form>
                          
                            </div>

                            <!--    <a type="submit" class="prev-btn" id="btnContinue" href="#">Cập nhập giỏ hàng</a> -->

                        </td>
                    </tr>
                </table>

            }
            else
            {
                <span class="alert alert-danger">Chưa có sản phẩm nào trong giỏ hàng</span>
           }
       }
       else
       {

            <script type="text/javascript">
                alert('Vui lòng đăng nhập.');
            </script>
          
       }



</div>

@section scripts{
                 
}

WebDT/Views/GioHang/PaymentOnline.cshtml
@*@model WebDT.Models.PayPalModel*@
@{
    ViewBag.Title = "Thanh toán";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
    var pay = (WebDT.Models.product)ViewBag.PaymentOnline;
}

@Styles.Render("~/css/detail")
@Scripts.Render("~/js/detail")

@*<form id="hiddenform" action=@Model.actionURL>
    @Html.HiddenFor(model => model.cmd)
    @Html.HiddenFor(model => model.business)
    @Html.HiddenFor(model => model.no_shipping)
    @Html.HiddenFor(model => model.@return)
    @Html.HiddenFor(model => model.cancel_return)
    @Html.HiddenFor(model => model.notify_url)
    @Html.HiddenFor(model => model.currency_code)
    @Html.HiddenFor(model => model.item_name)
    @Html.HiddenFor(model => model.item_quantity)
    @Html.HiddenFor(model => model.amount)
</form>*@  

<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">

            <div class="col-md-8">
                <div class="product-content-right">
                    <div class="product-breadcroumb">
                        @Html.ActionLink("Trang chủ", "Index", "Default")
                        <a href="">@pay.name</a>
                    </div>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="product-images">
                                <div class="product-main-img">
                                    <img src="~/Content/img/@pay.img" alt="">
                                </div>

                                <div class="product-gallery">
                                    <img src="img/product-thumb-1.jpg" alt="">
                                    <img src="img/product-thumb-2.jpg" alt="">
                                    <img src="img/product-thumb-3.jpg" alt="">
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="product-inner">
                                <h2 class="product-name">@pay.name</h2>
                                <div class="product-inner-price">
                                    @if (pay.newprice != null)
                                    { <ins>@string.Format("{0:0,0 VNĐ}", pay.newprice)</ins>
                                    <del>@string.Format("{0:0,0 VNĐ}", pay.price)</del> }
                                    else
                                    {
                                        <ins>@string.Format("{0:0,0 VNĐ}", pay.price)</ins>
                                    }
                                </div>

                                <div class="product-inner-category" style="margin-top:15px">
                                    <p>Thể loại: <a href="#">@pay.name</a></p>
                                </div>

                                <div role="tabpanel" style="width: 130%;">
                                    <ul class="product-tab" role="tablist">
                                        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Thanh toán khi nhận hàng</a></li>
                                        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Thanh toán online</a></li>
                                    </ul>
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane fade in active" id="home">
                                            @using (Html.BeginForm("ThanhToan", "GioHang", FormMethod.Post))

                                            {
                                                <h2 class="page-heading">
                                                    <span class="page-heading-title2" style="padding:2px 26%">Chi tiết đặt hàng</span>
                                                </h2>
                                                <input type="hidden" name="productId" value="@pay.id" />
                                                <input type="hidden" name="totalPrice" value="@pay.price" />
                                                <div class="form-group">
                                                    <label>Người nhận</label>
                                                    <input name="tenkhachhang" class="form-control" value="@Session["ten"].ToString()" readonly/>
                                                </div>
                                                <div class="form-group">
                                                    <label>Điện thoại</label>
                                                    <input name="sdt" class="form-control" />
                                                </div>
                                                <div class="form-group">
                                                    <label>Địa chỉ</label>
                                                    <input name="diachi" class="form-control" />
                                                </div>
                                                <div class="form-group">
                                                    <label>E-Mail</label>
                                                    <input name="email" class="form-control" />
                                                </div>
                                                <div class="form-group">
                                                    <label>Lời nhắn:</label>
                                                    <textarea name="noidung" id="loinhan" class="form-control" value="" onfocus="this.value = '';" onblur="if (this.value == '') { this.value = 'Lời nhắn ghi ở đây...'; }"></textarea>
                                                </div>

                                                <button type="submit" class="button pull-right" style="margin-right: 25px">Gửi đơn hàng</button>
                                            }
                                        </div>
                                        <div role="tabpanel" class="tab-pane fade" id="profile">
                                            <div class="submit-review">
                                                @using (Html.BeginForm("ValidateCommand", "GioHang", FormMethod.Post))
                                                {
                                                    <input type="hidden" name="product" value="@pay.name"/>
                                                    <input type="hidden" name="totalPrice" value="@pay.price" />
                                                    <input type="hidden" name="quantity" value="1" />
                                                    <p><label for="name">Họ Tên</label> <input name="name" type="text" value="@Session["ten"].ToString()" readonly></p>
                                                    <p><label for="phone">Số điện thoại</label> <input name="phone" type="text"></p>
                                                    <p><label for="adress">Địa chỉ</label> <input name="adress" type="text"></p>
                                                    <div class="rating-chooser">
                                                        <input type="submit" name="btnConfirm" class="btn btn-primary btn-block" value="Thanh toán online"/>
                                                    </div>
                                                }
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="product-images">
                            <div class="product-main-img">
                                <img src="img/product-2.jpg" alt="">
                            </div>

                            <div class="product-gallery">
                                <img src="img/product-thumb-1.jpg" alt="">
                                <img src="img/product-thumb-2.jpg" alt="">
                                <img src="img/product-thumb-3.jpg" alt="">
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

WebDT/Views/GioHang/Success.cshtml
@{
    ViewBag.Title = "Đặt hàng";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<div class="alert alert-success" style="text-align: center">

    Bạn vừa đặt hàng thành công.

</div>

WebDT/Views/GioHang/ThanhToan.cshtml
@model List<WebDT.Models.CartItem>
@{
    ViewBag.Title = "Thanh toán";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
    var totalPrice = 0;
}
@section jsFooter{
 
<script src="/Scripts/Controller/CartController.js"></script>
}

@if (ViewBag.error != null)
{
    <div class="alert alert-danger" style="text-align: center">
            @ViewBag.error
    </div>
}

<div class="columns-container"  style="padding: 20px; margin-left: 25pc;">
    <div class="container" id="columns">
        <div role="tabpanel" style="width: 50%;">
            <ul class="product-tab" role="tablist">
                @*<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Thanh toán khi nhận hàng</a></li>*@
                <li role="presentation"><a href="#profile" aria-controls="home" role="tab" data-toggle="tab">Thanh toán online</a></li>
            </ul>
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane fade in active" id="home">
                    @foreach (var item in Model)
                    {
                        totalPrice = totalPrice + (int)item.Product.price * item.Quantity;
                    }
                    @using (Html.BeginForm("ThanhToan", "GioHang", FormMethod.Post, new { id = "ThanhToan" }))

                    {
                        @*<h2 class="page-heading">
                            <span class="page-heading-title2" style="padding:20px">Chi tiết đặt hàng</span>
                        </h2>*@
                        @*<input type="hidden" name="productId" value="@pay.id" />
                        <input type="hidden" name="totalPrice" value="@pay.price" />*@
                        @*<input type="hidden" name="totalPrice" value="@totalPrice" />
                        <div class="form-group">
                            <label>Người nhận</label>
                            <input name="tenkhachhang" class="form-control" value="@Session["ten"].ToString()" readonly />
                        </div>
                        <div class="form-group">
                            <label>Điện thoại</label>
                            <input name="sdt" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Địa chỉ</label>
                            <input name="diachi" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>E-Mail</label>
                            <input name="email" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Lời nhắn:</label>
                            <textarea name="noidung" id="loinhan" class="form-control" value="" onfocus="this.value = '';" onblur="if (this.value == '') { this.value = 'Lời nhắn ghi ở đây...'; }"></textarea>
                        </div>

                        <button type="submit" class="button pull-right" style="margin-right: 25px">Gửi đơn hàng</button>*@
                    }
                    
                </div>
                <div role="tabpanel" class="tab-pane fade in active" id="home">
                    <div class="submit-review">
                        @using (Html.BeginForm("Payment", "AccountPayment", FormMethod.Post, new { id = "Payment" }))
                        {
                            <p><label for="phone">Số tài khoản</label> <input name="accountNumber" value="@Session["accountNumber"]" type="text" readonly></p>
                            <p><label for="adress">Tên chủ tài khoản</label> <input name="accountName" value="@Session["ten"].ToString().ToUpper()" type="text" readonly></p>
                            <div class="rating-chooser">
                                <input type="submit" name="btnConfirm" class="btn btn-primary btn-block" value="Thanh toán" />
                            </div>
                        }
                        @*Chưa có tài khoản thanh toán: <a href="/dang-ky-thanh-toan"> Đăng Ký </a>*@
                    </div>
                </div>
            </div>
        </div>
                
    </div>
</div>


               @section scripts{
                   <script type="text/javascript">

                       //validate phone number
                       $.validator.addMethod("validatePhone", function (value, element) {
                           return this.optional(element) || /(09|0[3|7|8|5])+([0-9]{8})\b/i.test(value);
                       }, "Số điện thoại không đúng");

                       //validate email
                       $.validator.addMethod("validateEmail", function (value, element) {
                           return this.optional(element) || /^(([^<>()\[\]\\.,;:\s@@"]+(\.[^<>()\[\]\\.,;:\s@@"]+)*)|(".+"))@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(value);
                       }, "Email sai");


                       $(document).ready(function () {

                           //Khi bàn phím được nhấn và thả ra thì sẽ chạy phương thức này
                           $("#ThanhToan").validate({
                               errorElement: "span",
                               rules: {
                                   diachi: {
                                       required: true
                                   },
                                   email: {
                                       required: true,
                                       validateEmail: true
                                   },
                                   sdt: {
                                       required: true,
                                       validatePhone: true
                                   }
                               },
                               messages: {
                                   diachi: {
                                       required: "Vui lòng nhập địa chỉ"
                                   },
                                   email: {
                                       required: "Vui lòng nhập địa chỉ email",
                                       validateEmail: "Địa chỉ email không đúng! Nhập lại."
                                   },
                                   sdt: {
                                       required: "Vui lòng nhập số điện thoại",
                                       validatePhone: "Số điện thoại không đúng! Nhập lại"
                                   }
                               }
                           });

                           $("#Payment").validate({
                               errorElement: "span",
                               rules: {
                                   accountNumber: {
                                       required: true,
                                       minlength: 14,
                                       maxlength: 14
                                   },
                                   accountName: "required"
                               },
                               messages: {
                                   accountNumber: {
                                       required: "Vui lòng nhập số thẻ",
                                       minlength: "Số thẻ không đúng, phải đủ 14 chữ số! Nhập lại",
                                       maxlength: "Số thẻ không đúng, phải đủ 14 chữ số! Nhập lại"
                                   },
                                   accountName: "Vui lòng nhập tên chủ thẻ"
                               }
                           });
                       });
                   </script>
               }

WebDT/Views/GioHang/ValidateCommand.cshtml
@{
    Layout = null;
}
@model WebDT.Models.PayPalModel   
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PayPal</title>
</head>
<body>
    <form id="hiddenform" action=@Model.actionURL>
        <input type="hidden" name="charset" value="utf-8">
        @Html.HiddenFor(model => model.cmd)
        @Html.HiddenFor(model => model.business)
        @Html.HiddenFor(model => model.no_shipping)
        @Html.HiddenFor(model => model.@return)
        @Html.HiddenFor(model => model.cancel_return)
        @Html.HiddenFor(model => model.notify_url)
        @Html.HiddenFor(model => model.currency_code)
        @Html.HiddenFor(model => model.item_name)
        @Html.HiddenFor(model => model.item_quantity)
        @Html.HiddenFor(model => model.amount)
    </form>

    <p style="text-align: center">
        <h3>
            Now you are connectin to the PayPal Application
        </h3>
    </p>  
</body>
@Scripts.Render("~/bundles/jquery")

<script type="text/javascript" language="javascript">

    $(this.document).ready(function () {
        var form = $("form");
        form.submit();
    });
</script>  
</html>