WebDT/Models/DangNhap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangNhap
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> buyLastDate { get; set; }
        public Nullable<int> countOrder { get; set; }
        public Nullable<double> amountSpent { get; set; }
        public Nullable<double> accountNumber { get; set; }
    }
}

WebDT/Areas/admin/Controllers/DangNhapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebDT.Models;

namespace WebDT.Areas.admin.Controllers
{
    public class DangNhapsController : Controller
    {
       
        private WebMayTinhEntities db = new WebMayTinhEntities();
        // GET: admin/DangNhaps
        public ActionResult Index()
        {
                var list = from DSKhachHang in db.DangNhaps
                           //where DSKhachHang.Quyenadmin == null && DSKhachHang.Quyenuser == null
                           select DSKhachHang;
                return View(list.ToList());
        }

        // GET: admin/DangNhaps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DangNhap dangNhap = db.DangNhaps.Find(id);
            if (dangNhap == null)
            {
                return HttpNotFound();
            }
            return View(dangNhap);
        }

        //Chart detail 
        public ActionResult UserChart()
        {
            var model = db.DangNhaps.Where(x => x.buyLastDate != null).ToList();
            var lstUser = new List<userChart>();

            //Tính ngày mua hàng gần nhất
            foreach(var item in model)
            {
                var userChart = new userChart();
                TimeSpan time = DateTime.Now - item.buyLastDate.Value;
                int Tongngay = time.Days;
                int soDonHang = int.Parse(item.countOrder.ToString());
                float soTienMua = float.Parse(item.amountSpent.ToString());
                userChart.Tongngay = Tongngay;
                userChart.soDonHang = soDonHang;
                userChart.soTienMua = soTienMua / 10000000;
                userChart.name = item.name;
                
                lstUser.Add(userChart);
            }
            return Json(lstUser, JsonRequestBehavior.AllowGet);
        }

        // GET: admin/DangNhaps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/DangNhaps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,username,password,name,address,email,phone,status")] DangNhap dangNhap)
        {
            if (ModelState.IsValid)
            {
                db.DangNhaps.Add(dangNhap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dangNhap);
        }

        // GET: admin/DangNhaps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DangNhap dangNhap = db.DangNhaps.Find(id);
            if (dangNhap == null)
            {
                return HttpNotFound();
            }
            return View(dangNhap);
        }

        // POST: admin/DangNhaps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,username,password,name,address,email,phone,status")] DangNhap dangNhap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dangNhap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dangNhap);
        }

        // GET: admin/DangNhaps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DangNhap dangNhap = db.DangNhaps.Find(id);
            if (dangNhap == null)
            {
                return HttpNotFound();
            }
            return View(dangNhap);
        }

        // POST: admin/DangNhaps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DangNhap dangNhap = db.DangNhaps.Find(id);
            db.DangNhaps.Remove(dangNhap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            return Redirect("http://localhost:54398");
        }
    }
}

WebDT/Controllers/TaiKhoanController.cs
using Facebook;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Numerics;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebDT.Models;

namespace WebDT.Controllers
{
    public class TaiKhoanController : Controller
    {
        //jk
        WebMayTinhEntities _db = new WebMayTinhEntities();
        SignalModel sig = new SignalModel();

        // GET: TaiKhoan
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {

            return View();
        }
        [HttpPost]
        public ActionResult DangKy(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var us = new User();
                if (us.CheckUserName(model.username))
                {
                    ViewBag.Success = "Tên đăng nhập đã tồn tại!";
                }
                //else if (us.CheckEmail(model.email))
                //{
                //    ViewBag.Success = "Email đã tồn tại!";
                //}
                else
                {
                    var user = new DangNhap();
                    user.username = model.username;
                    user.password = model.password;
                    user.name = model.name;
                    user.accountNumber = model.accountNumber;
                    user.countOrder = 0;
                    user.amountSpent = 0;
                    user.status = true;

                    var acc = new AccountPayment();
                    acc.accountNumber = model.accountNumber;
                    acc.accountName = model.name.ToUpper();
                    acc.accountBalance = 100000000;

                    //Tạo khóa công khai
                    List<BigInteger> khoa = sig.TaoKhoa();
                    acc.so_p = khoa[1].ToString().Trim();
                    acc.so_t = khoa[2].ToString().Trim();
                    acc.so_q = khoa[3].ToString().Trim();

                    //Tạo khóa bí mật và mã hóa
                    acc.pri_key = sig.Encrypt_MD5(khoa[0].ToString());

                    acc.status = true;
                    _db.AccountPayments.Add(acc);
                    _db.SaveChanges();

                    var result = us.Insert(user);
                    if (result)
                    {
                        
                        ViewBag.Success = "Đăng ký thành công";
                        model = new RegisterModel();
                        return Redirect("/dang-nhap");
                    }
                    else
                    {
                        ViewBag.Success = "Đăng ký không thành công!";
                    }
                }
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(ModelLogin model , String username )
        {
            if (ModelState.IsValid)
            {
               
                var ad = new User();
                var result = ad.Login(model.UserName, model.Password);
                var obj = _db.DangNhaps.Where(a=> a.username.Equals(username)).FirstOrDefault();

                if (result == 1)
                {
                    var user = ad.getById(model.UserName);
                    var userSession = new UserLogin();
                    userSession.UserName = user.username;                 
                    userSession.UserID = user.id;               
                    Session["UserName"] = model.UserName.ToString();
                    Session["ten"] = obj.name.ToString();
                    Session["admin"] =  obj.username.Trim();
                    //Session["User"] = obj.Quyenuser;
                    //Session["phone"] = obj.phone.ToString();
                    //Session["DiaChi"] = obj.address.ToString();
                    //Session["Email"] = obj.email.ToString();
                    Session["accountNumber"] = obj.accountNumber.ToString();

                    //var listCredential = ad.GetListCredential(model.UserName);
                    //Session.Add(CommonConstants.SESSION_CREDENTIALS, listCredential);
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                    //var t = 'admin';
                   if (Session["admin"].ToString() == "admin")
                    {
                        return Redirect("http://localhost:54398/admin");
    
                    }
                    //else
                    //if( Session["User"]!=null)
                    //{
                    //    return Redirect("http://localhost:54398/admin");
                        
                    //}
                   else
                    {
                        return RedirectToAction("Index", "Default");
                    }
                   
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoảng không tồn tại!");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoảng đang bị khóa!");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng!");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng nhập không thành công!");
                }
            }
            return View(model);

        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
        

        public ActionResult QuyenMatKhau(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DangNhap TaiKhoan = _db.DangNhaps.Find(id);
            if (TaiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(TaiKhoan);
        }
      

        //Danh sách hóa đơn đã đặt hàng của khách hàng.
        public ActionResult DanhSachHoaDon()
        {
           
            string user = Session["UserName"].ToString();
            List<DsSP> models = null;
            if (!string.IsNullOrEmpty(user)) //IsNullOrEmpty là cho biết chuỗi đã chỉ định là null hay rỗng
            {
                models = (from sp in _db.products
                          join chitietgh in _db.ChiTietGioHangs on sp.id equals chitietgh.IDSanPham
                          join giohangs in _db.GioHangs on chitietgh.IDGioHang equals giohangs.id
                          join taikhoankh in _db.DangNhaps on giohangs.IDKhachHang equals taikhoankh.username
                          where giohangs.IDKhachHang == user
                          select new DsSP()
                          {                            
                              TaiKhoan = taikhoankh.username,
                              Tensp = sp.name,
                              Hinh = sp.img,
                              Tien = chitietgh.Tien,
                              SoLuong = chitietgh.SoLuong,
                              NgayDat = giohangs.NgayTao,
                          }).ToList();
            }
            return View(models);
        }       
    }
}

WebDT/Views/TaiKhoan/DangKy.cshtml
@model WebDT.Models.RegisterModel
@{
    ViewBag.Title = "Đăng ký";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<div class="content">
    @using (Html.BeginForm("DangKy", "TaiKhoan", FormMethod.Post, new { id = "RegisterUser" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            
            <h4 style="margin-top: 20px; margin-left:45%"> <b>Đăng ký thành viên</b> </h4>
            <hr />
            <div class="form-group" >
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @if (ViewBag.Success != null)
                {
                    <div class="alert alert-success"><p style="margin-left: 45%">@ViewBag.Success</p></div>
                }
            </div>
            <div class="form-group" style="margin-left:25%">
                @Html.LabelFor(model => model.username, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.username, new { @class = "form-control", name = "username" })
                    @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="margin-left:25%">
                @Html.LabelFor(model => model.password, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.password, new { @class = "form-control", name = "password", id = "password" })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="margin-left:25%">
                @Html.LabelFor(model => model.confirmpassword, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.confirmpassword, new { @class = "form-control", name = "confirmpassword" })
                    @Html.ValidationMessageFor(model => model.confirmpassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="margin-left:25%">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.name, new { @class = "form-control", name = "name" })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="margin-left:25%">
                @Html.LabelFor(model => model.accountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.accountNumber, new { @class = "form-control",name = "accountNumber" })
                    @Html.ValidationMessageFor(model => model.accountNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="margin-left:25%">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Đăng ký" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>


@section jsFooter{
    <script type="text/javascript">

        $(document).ready(function () {

            //Khi bàn phím được nhấn và thả ra thì sẽ chạy phương thức này
            $("#RegisterUser").validate({
                errorElement: "span",
                rules: {
                    username: {
                        required: true,
                        minlength: 5,
                    },
                    password: {
                        required: true,
                        minlength: 6,
                    },
                    confirmpassword: {
                        required: true,
                        equalTo: "#password"
                    },
                    name: {
                        required: true,
                        minlength: 5
                    },
                    accountNumber: {
                        required: true,
                        minlength: 14,
                        maxlength: 14
                    }
                },
                messages: {
                    username: {
                        required: "Vui lòng nhập tên đăng nhập",
                        minlength: "Tên đăng nhập phải ít nhất 5 ký tự"
                    },
                    password: {
                        required: "Vui lòng nhập mật khẩu",
                        minlength: "Tên mật khẩu phải ít nhất 6 ký tự"
                    },
                    confirmpassword: {
                        required: "Vui lòng nhập lại mật khẩu",
                        equalTo: 'Mật khẩu không trùng'
                    },
                    name: {
                        required: "Vui lòng nhập họ và tên",
                        minlength: "Họ và tên phải ít nhất 5 ký tự"
                    },
                    accountNumber: {
                        required: "Vui lòng nhập số thẻ",
                        minlength: "Số thẻ không đúng, phải đủ 14 chữ số! Nhập lại",
                        maxlength: "Số thẻ không đúng, phải đủ 14 chữ số! Nhập lại"
                    }                    
                }
            });
        });
    </script>
}

WebDT/Views/TaiKhoan/DangNhap.cshtml
@model WebDT.Models.ModelLogin

@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<div class="content">
    @using (Html.BeginForm("DangNhap", "TaiKhoan", FormMethod.Post))
            {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 style="margin-top: 20px; margin-left:45%"> <b>Đăng nhập</b> </h4>
            <hr />
           @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group" style="margin-left: 27%">
                @Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-2" })
                <div class="col-md-6" style="width: 70%">
                    @Html.TextBoxFor(model => model.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="margin-left: 27%">
                @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
                <div class="col-md-6" style="width: 70%">
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="margin-left: 27%">
                <div class="col-md-offset-2 col-md-10" >
                    <input type="submit" value="Đăng nhập" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

WebDT/Views/TaiKhoan/DanhSachHoaDon.cshtml
@model List<WebDT.Models.DsSP>
@{
    ViewBag.Title = "Đơn hàng đã mua";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@section jsFooter{
    <script src="~/Scripts/Controller/cartController.js"></script>}


<div >
    <h2 style="padding:20px 0px; text-align:center; color:red;background-color:#bdf998"><b>DANH SÁCH SẢN PHẨM ĐÃ MUA</b></h2> 

</div>

<table cellspacing="0" class="shop_table cart">
    <thead>
        <tr>
            <th class="product-thumbnail">Hình ảnh</th>
            <th class="product-name">Tên sản phẩm</th>
            <th class="product-quantity">Số lượng</th>
            <th class="product-subtotal">Tổng giá(VNĐ)</th>
            <th class="product-price">Ngày đặt</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model)
        {
            <tr class="cart_item">

                <td class="product-thumbnail">
                    <a href="#"><img width="145" height="145" alt="poster_1_up" class="shop_thumbnail" src="~/Content/img/@i.Hinh"></a>
                </td>

                <td class="product-name" style="text-align:left" >
                    <a href="#">@i.Tensp</a>
                </td>

                <td class="product-price">
                    <a>@i.SoLuong</a>
                </td>

                <td class="product-quantity">
                    <a>@i.Tien</a>
                </td>
                <td class="product-name">
                    <a href="#">@i.NgayDat</a>
                </td>
            </tr>
        }

    </tbody>
</table>